package com.auditiq.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "anomaly_result")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AnomalyResult {

    // private UUID id;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transaction_fk")
    private Transaction transaction;

    @ElementCollection
    @CollectionTable(name = "anomaly_flags", joinColumns = @JoinColumn(name = "anomaly_id"))
    @Column(name = "flag")
    private List<String> flags;

    // LOW, MEDIUM, HIGH, CRITICAL
    private String severity;

    // raw numeric score before bucketing — store for transparency
    private Integer severityScore;

    // human-readable, generated by ExplanationAgent
    @Column(columnDefinition = "TEXT")
    private String explanation;

    private LocalDateTime detectedAt;
}
