
spring.application.name=auditIq

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/auditiq_db
spring.datasource.username=gauravjoshi
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Server configuration
server.port=8082

# File Upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
