
spring.application.name=auditIq

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/auditiq_db
spring.datasource.username=gauravjoshi
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Server configuration
server.port=8082

# File Upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MAIL configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gaurav12asap@gmail.com
spring.mail.password=tmjf dums rrem zdlx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=5c4f2a89d7c3b1e6f4a28d7b3e1c9f5a8b2d4e6c7a1f3b5d9e8c4a2b1f7d3e9
jwt.expiration=86400000